name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: windows-2022
    steps:
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GHF }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            test.txt
