name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Check code format (editorconfig)
        run: dotnet format --verify-no-changes
      - name: Test (Release)
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Publish executable (Release)
        run: dotnet publish -c Release --framework net6.0 --self-contained false --runtime linux-x64 -p:PublishTrimmed=false -p:PublishSingleFile=true -p:PublishReadyToRun=true src/custom-data.client/custom-data.client.csproj
      - name: Get Version
        run: src/custom-data.client/bin/Release/net6.0/linux-x64/publish/custom-data.client
